### ISSUE TITLE
Crash при пролистывании вниз при обновлении контента

### ISSUE THREAD

**Issue by getsmp** [getsmp/LOR-for-Android#16]
1. Зайти в трекер.
2. Потянуть вниз.
3. Пока SwipeRefreshLayout виден, пролистать вниз.

**Comment by getsmp** [comment]
Stacktrace
```java
:34.252 12504-12504/io.github.getsmp.lorforandroid E/InputEventReceiver: Exception dispatching input event.
01-22 19:09:34.255 12504-12504/io.github.getsmp.lorforandroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: io.github.getsmp.lorforandroid, PID: 12504
                                                                                java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 5(offset:5).state:30
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4405)
                                                                                    at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
                                                                                    at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
                                                                                    at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
                                                                                    at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
                                                                                    at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)
                                                                                    at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1018)
                                                                                    at android.support.v7.widget.RecyclerView.scrollByInternal(RecyclerView.java:1492)
                                                                                    at android.support.v7.widget.RecyclerView.onTouchEvent(RecyclerView.java:2416)
                                                                                    at android.view.View.dispatchTouchEvent(View.java:8538)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2541)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2220)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
                                                                                    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2455)
                                                                                    at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1757)
                                                                                    at android.app.Activity.dispatchTouchEvent(Activity.java:2787)
                                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                    at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                                    at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2404)
                                                                                    at android.view.View.dispatchPointerEvent(View.java:8760)
                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4718)
                                                                                    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4566)
                                                                                    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4085)
                                                                                    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4144)
                                                                                    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4110)
                                                                                    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4223)
                                                                                    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4118)
                                                                                    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4280)
                                                                                	at
```

**Comment by getsmp** [comment]
Баг RecyclerView
https://code.google.com/p/android/issues/detail?can=1&q=77846&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars&id=77846
