### ISSUE TITLE
Parcel: unable to marshal value

### ISSUE THREAD

**Issue by getsmp** [getsmp/LOR-for-Android#78]
Introduced in 00eaa626b9f5a14114cd378f4c245b3dd5f8bd1c
`Process: io.github.getsmp.lorforandroid, PID: 25530
                                                                                java.lang.RuntimeException: Parcel: unable to marshal value io.github.getsmp.lorforandroid.ui.section.ItemCommon@6d8d483
                                                                                    at android.os.Parcel.writeValue(Parcel.java:1337)
                                                                                    at android.os.Parcel.writeList(Parcel.java:711)
                                                                                    at android.os.Parcel.writeValue(Parcel.java:1284)
                                                                                    at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                                                                                    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                                    at android.os.Bundle.writeToParcel(Bundle.java:1096)
                                                                                    at android.os.Parcel.writeBundle(Parcel.java:663)
                                                                                    at android.support.v4.app.FragmentState.writeToParcel(Fragment.java:138)
                                                                                    at android.os.Parcel.writeTypedArray(Parcel.java:1191)
                                                                                    at android.support.v4.app.FragmentManagerState.writeToParcel(FragmentManager.java:385)
                                                                                    at android.os.Parcel.writeParcelable(Parcel.java:1357)
                                                                                    at android.os.Parcel.writeValue(Parcel.java:1262)
                                                                                    at android.os.Parcel.writeArrayMapInternal(Parcel.java:638)
                                                                                    at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1313)
                                                                                    at android.os.Bundle.writeToParcel(Bundle.java:1096)
                                                                                    at android.os.Parcel.writeBundle(Parcel.java:663)
                                                                                    at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3025)
                                                                                    at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3696)
                                                                                    at android.os.Handler.handleCallback(Handler.java:810)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                    at android.os.Looper.loop(Looper.java:209)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5916)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1005)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:800)
`

**Comment by getsmp** [comment]
Reintroduced in db327590
